### ISSUE TITLE
Error in optim step when running steps manually

### ISSUE THREAD

**Issue by alhaas** [AntaresSimulatorTeam/antares-xpansion#142]
When running the steps (antares, getnames, lp, optim) manually the optim step fails to execute as it is looking for the `simulation_name` (which is set by `generate_mps_files` in full mode?) attribute instead of the `simulationname` attribute.

 ```
C:\temp\XPansion\antaresXpansion-0.3.0-win64>antares-xpansion-launcher.exe -i examples\SmallTestFiveCandidates -m mpibenders --installDir bin --simulationName 20210518-1624eco --step optim
Traceback (most recent call last):
  File "launch.py", line 13, in <module>
  File "antares_xpansion\driver.py", line 239, in launch
  File "antares_xpansion\driver.py", line 487, in launch_optimization
AttributeError: 'XpansionDriver' object has no attribute 'simulation_name'
[11972] Failed to execute script launch
```

**Comment by sgatto** [comment]
Hello,
thanks for report. I will look into this

**Comment by sgatto** [comment]
We identified the bug.
After further checks and reviews we will post a corrected version.
