### ISSUE TITLE
Error when using the Antares "playlist" function

### ISSUE THREAD

**Issue by MathildeFranconRTE** [AntaresSimulatorTeam/antares-xpansion#45]
[xpansion-test-02.zip](https://github.com/AntaresSimulatorTeam/antares-xpansion/files/6034878/xpansion-test-02.zip)

The use of the "MC scenario playlist" function to run Antares over 3 MC years out of the 10 MC years did not work on the test_case study (but it worked on a previous version of the open-source version of Xpansion) 

Traceback (most recent call last):
  File "launch.py", line 11, in <module>
  File "antares_xpansion\driver.py", line 219, in launch
  File "antares_xpansion\driver.py", line 483, in generate_mps_files
  File "antares_xpansion\driver.py", line 287, in pre_antares
  File "configparser.py", line 697, in read
  File "configparser.py", line 1093, in _read
configparser.DuplicateOptionError: While reading from 'E:\\AppliRTE\\Documents\\antaresXpansion\\Opensource\\antaresXpansion-0.1.0-win64\\antaresXpansion-0.1.0-win64\\examples\\xpansion-test-01\\settings\\generaldata.ini' [line 75]: **option 'playlist_year +' in section 'playlist' already exists**
[11772] Failed to execute script launch

**Comment by jmkerloch** [comment]
python module `configparser` is used to parse .ini files.

By default, if there are multiple section with same name a `DuplicateOptionError `is thrown.

**Comment by jmkerloch** [comment]
There is also an issue with `antares-solver` in case of playlist use with `antares-xpansion` : 

```
python launch.py --step full --dataDir ../../../xpansion-test-02
['pv', 'battery', 'semibase1', 'semibase2', 'peak1', 'peak2']
starting mps generation
-- pre antares
-- launching antares
['C:\\Projet_SRO\\rte-antares\\antares-xpansion-installer-64bits\\antaresXpansion-0.1.0-win64\\bin\\antares-8.0-solver.exe', 'C:\\Projet_SRO\\rte-antares\\xpansion-test-02']
['20210224-1534eco', 'maps']
['20210224-1534eco', '20210224-1542eco', 'maps']
-- post antares
Traceback (most recent call last):
  File "launch.py", line 12, in <module>
    DRIVER.launch()
  File "C:\Projet_SRO\rte-antares\antares-xpansion-installer-64bits\antaresXpansion-0.1.0-win64\xpansion-launcher\antares_xpansion\driver.py", line 219, in launch
    lp_path = self.generate_mps_files()
  File "C:\Projet_SRO\rte-antares\antares-xpansion-installer-64bits\antaresXpansion-0.1.0-win64\xpansion-launcher\antares_xpansion\driver.py", line 489, in generate_mps_files
    lp_path = self.post_antares(antares_output_name)
  File "C:\Projet_SRO\rte-antares\antares-xpansion-installer-64bits\antaresXpansion-0.1.0-win64\xpansion-launcher\antares_xpansion\driver.py", line 343, in post_antares
    self.get_names(antares_output_name)
  File "C:\Projet_SRO\rte-antares\antares-xpansion-installer-64bits\antaresXpansion-0.1.0-win64\xpansion-launcher\antares_xpansion\driver.py", line 370, in get_names
    assert len(area_files) == 1
AssertionError

```

No `area.txt` file is created by `antares-solver`

**Comment by jmkerloch** [comment]
After checking `antares-solver` code, `area.txt` file is created only for the first year of the simulation. See `src/solver/optimisation/opt_export_structure.cpp` : 

```
void OPT_ExportAreaName(const Antares::Data::Study& study, uint numSpace)
{
    // Area name are exported only once for first year
    if (study.runtime->currentYear[numSpace] == 0 && study.runtime->weekInTheYear[numSpace] == 0)
    {
        FILE* Flot = study.createFileIntoOutputWithExtension("area", "txt", numSpace);
        for (uint i = 0; i < study.areas.size(); ++i)
        {
            fprintf(Flot, "%s\n", study.areas[i]->name.c_str());
        }
        fclose(Flot);
    }
} 
```
