### ISSUE TITLE
Unknown error on the test cas xpansion-test-02

### ISSUE THREAD

**Issue by MathildeFranconRTE** [AntaresSimulatorTeam/antares-xpansion#46]
[xpansion-test-02.zip](https://github.com/AntaresSimulatorTeam/antares-xpansion/files/6034875/xpansion-test-02.zip)

Traceback (most recent call last):
  File "launch.py", line 9, in <module>
  File "antares_xpansion\driver.py", line 36, in __init__
  File "antares_xpansion\driver.py", line 280, in check_settings
  File "antares_xpansion\input_checker.py", line 452, in check_settings_file
  File "antares_xpansion\input_checker.py", line 452, in <dictcomp>
IndexError: list index out of range
[2716] Failed to execute script launch

**Comment by jmkerloch** [comment]
There are some empty lines at the end of `xpansion-test-02/user/expansion/settings.ini`

This is currently not supported.

Correction : 

- [ ] update `src/src_python/input_checker.py` so empty line are not checked
