### ISSUE TITLE
Error while writing basis with COIN

### ISSUE THREAD

**Issue by tbittar** [AntaresSimulatorTeam/antares-xpansion#493]
On the example `SmallTestFiveCandidates`, there is an error when `COIN` writes the basis at the end of the Benders step :

```
Illegal index 941 in ClpModel::setRowName
terminate called after throwing an instance of 'CoinError'
Traceback (most recent call last):
  File "launch.py", line 39, in <module>
  File "antares_xpansion/driver.py", line 69, in launch
  File "antares_xpansion/driver.py", line 116, in launch_benders_step
  File "antares_xpansion/benders_driver.py", line 59, in launch
antares_xpansion.benders_driver.BendersExecutionError: ERROR: exited solver with status -6
[74881] Failed to execute script 'launch' due to unhandled exception!
```

**Comment by tbittar** [comment]
The issue is that at the last iteration, we solve the master, the subproblems and we add new cuts, that will not be useful (as the algorithm stops). 

In the COIN interface, `_clp_inner_solver` has these last cuts, whereas `_cbc.solver()` does not, which was causing the issue, when trying to update row names of `_cbc.solver()` from the ones of `_clp_inner_solver`.
