### ISSUE TITLE
AntaresXpansion - number of MC years

### ISSUE THREAD

**Issue by DraganaOrlic** [AntaresSimulatorTeam/antares-xpansion#688]
It seems that it is not possible to run AntaresXpansion with more than 9 MC years. Please see example that comes with installation ("SmallTestSixCandidatesWithPlaylist")  that does not work with all 10 MC years. 

Regards,
Dragana

**Comment by tbittar** [comment]
Hello, I do not understand the problem, if the playlist is parametrized to use all years from 0 to 9 in this study, Xpansion should run with all these years. Could you give more details on the issue you encountered so that I can reproduce it ?

Regards,
Thomas

**Comment by DraganaOrlic** [comment]
Dear Thomas

Many thanks for the reply.

Please see example that comes with installation ("SmallTestSixCandidatesWithPlaylist") , which includes 10 MC years but  does not work with all 10 MC years.

The version I am talking about can be found at:
https://github.com/AntaresSimulatorTeam/antares-xpansion/releases/download/v1.0.3-rc1/antaresXpansion-1.0.3-xpress-windows-single-file.zip


If you activate MC years 1-9 or 2-10 or just use 3 selected MC years as you can find in the Antares model when you open the example - AntaresXpansion works but if you activate all 10 the following messages are obtained:

----------------------------------------------------------------
Running Antares Xpansion ...
Xpansion version: 1.0.3
antares simulator version: 8.5.0-rc3
----------------------------------------------------------------
D:\Antares\antaresXpansion-xpress-1.0.3-win64\examples\SmallTestSixCandidatesWithPlaylist is locked
<< INFO >> No solver defined in user/expansion/settings.ini. Cbc used
-- pre antares
-- launching antares
Antares simulation duration : 0:00:27.069285
-- post antares
-- Problem Generation
Post antares step duration: 0:00:47.279224
-- Benders
Current directory is now: D:\Antares\antaresXpansion-xpress-1.0.3-win64\examples\SmallTestSixCandidatesWithPlaylist\output\20230929-0916eco-Xpansion\lp
Traceback (most recent call last):
File "launch.py", line 39, in <module>
File "antares_xpansion\driver.py", line 72, in launch
File "antares_xpansion\driver.py", line 139, in launch_benders_step
File "antares_xpansion\benders_driver.py", line 58, in launch
antares_xpansion.benders_driver.BendersDriver.BendersExecutionError: ERROR: exited solver with status 3221226505
[3084] Failed to execute script 'launch' due to unhandled exception!

Hope you can help us…We would like to implement AntaresXpansion on 35 MC years, but with this error we cannot move over 9 MC.

Best regards,
Dragana

**Comment by JasonMarechal25** [comment]
Hello. Thank you for those details.

Just so that I can be sure to understand properly, when you say "activate all 10" you're saying something like this in generaldata.ini:

```[playlist]
playlist_reset = false
playlist_year + = 0
playlist_year + = 1
playlist_year + = 2
playlist_year + = 3
playlist_year + = 4
playlist_year + = 5
playlist_year + = 6
playlist_year + = 7
playlist_year + = 8
playlist_year + = 9
```

**Comment by DraganaOrlic** [comment]
Yes, yes.. all 10 should be "true"

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by a-zakir** [comment]
Hello @DraganaOrlic , it's in dev, could you try one of the artifacts [here](https://github.com/AntaresSimulatorTeam/antares-xpansion/actions/runs/6466502606)

**Comment by a-zakir** [comment]
> Hello @DraganaOrlic , it's in dev, could you try one of the artifacts [here](https://github.com/AntaresSimulatorTeam/antares-xpansion/actions/runs/6466502606)

**Comment by DraganaOrlic** [comment]
Hello Zakir

Thanks for the changes…it works now on small example.
However, I am still struggling to run antaresXpansion on the whole Europe and 35 MC years…I works for 11 MC year (maybe more) but not for 35.
Do you think that benders is the problem? Do you have an idea how to overcome this?

Best regards
Dragana

**Comment by DraganaOrlic** [comment]
Thanks all

Can you send me the link to new installation please…

Best
Dragana

**Comment by a-zakir** [comment]
Hello @DraganaOrlic , thanks for your feedbacks, i think we are facing memory problem, in fact on my local machine (windows) the study does not work for 35 mc years (it takes a minimum of 25Gb for 25MC years).
[here](https://github.com/AntaresSimulatorTeam/antares-xpansion/actions/runs/6572696835) you can find the latest version of the fix. Still this issue has permitted to fix some [bugs](https://github.com/AntaresSimulatorTeam/antares-xpansion/pull/697)

i reopen this discussion...

**Comment by DraganaOrlic** [comment]
Hello a-zakir and thanks for trying to solve this issue. Unfortunately, the latest version (https://github.com/AntaresSimulatorTeam/antares-xpansion/actions/runs/6572696835) 
cannot run either 1 MC for the European model for which the previous version managed to work with 11 MC years.
