### ISSUE TITLE
antares-xpansion 1.3.0-rc2 doesn't work on ubuntu 20.04

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/antares-xpansion#840]
1. Use example study SmallFiveCandidates
2. Use the single-file install @ 1.3.0-rc2
3. Error message looks like
```
./antaresXpansion-1.3.0/antares-xpansion-launcher -i SmallTestFiveCandidates-1.3.0
----------------------------------------------------------------
[Pre Antares][INFO 07-06-2024 15:38:36]  Running Antares Xpansion ... 
[Pre Antares][INFO 07-06-2024 15:38:36]  user: omnesflo
[Pre Antares][INFO 07-06-2024 15:38:36]  hostname: gm0winl370.bureau.si.interne
[Pre Antares][INFO 07-06-2024 15:38:36]  Xpansion version: 1.3.0
[Pre Antares][INFO 07-06-2024 15:38:36]  antares simulator version: 8.8
----------------------------------------------------------------
[StudyLocker][INFO 07-06-2024 15:38:36]  SmallTestFiveCandidates-1.3.0 is locked
[ProfileLinkChecker][INFO 07-06-2024 15:38:36]  In candidate 3 description, deprecated option: **link-profile** is replaced by **direct-link-profile** and **indirect-link-profile** options
[SplitLinkProfile][INFO 07-06-2024 15:38:36]  Direct link profile: direct_capa_pv.ini is created from link-profile file: capa_pv.ini
[ProfileLinkChecker][INFO 07-06-2024 15:38:36]  In candidate 5 description, deprecated option: **link-profile** is replaced by **direct-link-profile** and **indirect-link-profile** options
[SplitLinkProfile][INFO 07-06-2024 15:38:36]  Direct link profile: direct_04_fr-05_fr.txt is created from link-profile file: 04_fr-05_fr.txt
[SplitLinkProfile][INFO 07-06-2024 15:38:36]  Direct link profile: direct_04_fr-05_fr.txt is created from link-profile file: 04_fr-05_fr.txt
[SplitLinkProfile][INFO 07-06-2024 15:38:36]  Indirect link profile: indirect_04_fr-05_fr.txt is created from link-profile file: 04_fr-05_fr.txt
[SplitLinkProfile][INFO 07-06-2024 15:38:36]  Indirect link profile: indirect_04_fr-05_fr.txt is created from link-profile file: 04_fr-05_fr.txt
[ProfileLinkChecker][INFO 07-06-2024 15:38:36]  candidates.ini is updated.
[ConfigLoader][INFO 07-06-2024 15:38:36]  No solver defined in user/expansion/settings.ini. Cbc used
[GeneralDataProcessor][INFO 07-06-2024 15:38:36]  Pre Antares
[AntaresDriver][INFO 07-06-2024 15:38:36]  Launching antares
[AntaresDriver][INFO 07-06-2024 15:38:42]  Antares simulation duration : 0:00:06.369555
[XpansionDriver][INFO 07-06-2024 15:38:42]  Post Antares
[FullRunDriver][INFO 07-06-2024 15:38:42]  Current directory is now: /home/omnesflo/Téléchargements/antaresXpansion-1.3.0/examples/SmallTestFiveCandidates/output/20240607-1538eco-Xpansion/lp
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    opal_init:startup:internal-failure
But I couldn't open the help file:
    /home/runner/work/antares-xpansion/antares-xpansion/vcpkg_installed/x64-linux/share/openmpi/openmpi/help-opal-runtime.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    orte_init:startup:internal-failure
But I couldn't open the help file:
    /home/runner/work/antares-xpansion/antares-xpansion/vcpkg_installed/x64-linux/share/openmpi/openmpi/help-orte-runtime: No such file or directory.  Sorry!
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    mpi_init:startup:internal-failure
But I couldn't open the help file:
    /home/runner/work/antares-xpansion/antares-xpansion/vcpkg_installed/x64-linux/share/openmpi/openmpi/help-mpi-runtime.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[gm0winl370.bureau.si.interne:1607429] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
Traceback (most recent call last):
  File "launch.py", line 51, in <module>
  File "antares_xpansion/driver.py", line 79, in launch
  File "antares_xpansion/full_run_driver.py", line 60, in launch
  File "antares_xpansion/full_run_driver.py", line 73, in run
antares_xpansion.full_run_driver.FullRunExecutionError: ERROR: exited /tmp/_MEIYpv85q/bin/full_run with status 1
[1606977] Failed to execute script 'launch' due to unhandled exception!
```

**Comment by a-zakir** [comment]
dear @flomnes thank you, i'il dive in

**Comment by a-zakir** [comment]
[just for record]
we rely on vcpkg to provide mpi lib, and it delivers  libmpi v4.x.x.
this issue can be solved on ubuntu by installing **libopenmpi3**

**Comment by a-zakir** [comment]
https://github.com/AntaresSimulatorTeam/antares-xpansion/issues/844
