### ISSUE TITLE
StudyUpdaterDriver issue

### ISSUE THREAD

**Issue by JasonMarechal25** [AntaresSimulatorTeam/antares-xpansion#908]
There are some issues with study update at the end of Xpansion simulation

Does not seem to affect every study.

`[StudyUpdaterDriver][INFO 02-09-2024 11:00:53]  Study Update
Traceback (most recent call last):
  File "/home/marechaljas/CLionProjects/antares-xpansion/src/python/launch.py", line 51, in <module>
    DRIVER.launch()
  File "/home/marechaljas/CLionProjects/antares-xpansion/src/python/antares_xpansion/driver.py", line 95, in launch
    self.study_update_driver.launch(
  File "/home/marechaljas/CLionProjects/antares-xpansion/src/python/antares_xpansion/study_updater_driver.py", line 42, in launch
    raise StudyUpdaterDriver.UpdaterExecutionError(
antares_xpansion.study_updater_driver.UpdaterExecutionError: ERROR: exited study-updater with status 1`

**Comment by JasonMarechal25** [comment]
Moved to internal ticketing system https://gopro-tickets.rte-france.com/browse/ANT-2194
